// 低学年の子どもが思い出しやすい代表的な読みと、短い意味。
export const READINGS = {
  "大": { reading: "おおきい", meaning: "おおきい もの" },
  "小": { reading: "ちいさい", meaning: "ちいさい もの" },
  "一": { reading: "いち", meaning: "かずの 1" },
  "二": { reading: "に", meaning: "かずの 2" },
  "三": { reading: "さん", meaning: "かずの 3" },
  "四": { reading: "よん", meaning: "かずの 4" },
  "五": { reading: "ご", meaning: "かずの 5" },
  "六": { reading: "ろく", meaning: "かずの 6" },
  "七": { reading: "なな", meaning: "かずの 7" },
  "八": { reading: "はち", meaning: "かずの 8" },
  "九": { reading: "きゅう", meaning: "かずの 9" },
  "十": { reading: "じゅう", meaning: "かずの 10" },
  "子": { reading: "こ", meaning: "こども" },
  "空": { reading: "そら", meaning: "そらの ひろがり" },
  "男": { reading: "おとこ", meaning: "おとこの ひと" },
  "女": { reading: "おんな", meaning: "おんなの ひと" },
  "手": { reading: "て", meaning: "ものを もつ ところ" },
  "天": { reading: "てん", meaning: "そらの うえ" },
  "青": { reading: "あお", meaning: "そらや うみの いろ" },
  "見": { reading: "みる", meaning: "めで たしかめる" },
  "学": { reading: "まなぶ", meaning: "べんきょうする" },
  "校": { reading: "こう", meaning: "べんきょうする ところ" },
  "虫": { reading: "むし", meaning: "ちいさな いきもの" },
  "文": { reading: "ぶん", meaning: "ことばを つないだもの" },
  "字": { reading: "じ", meaning: "かいた もじ" },
  "正": { reading: "ただしい", meaning: "まちがって いない" },
  "山": { reading: "やま", meaning: "たかい もりあがり" },
  "水": { reading: "みず", meaning: "のんだり あらう もの" },
  "雨": { reading: "あめ", meaning: "そらから ふる みず" },
  "上": { reading: "うえ", meaning: "たかい ほう" },
  "下": { reading: "した", meaning: "ひくい ほう" },
  "日": { reading: "ひ", meaning: "そらの たいよう" },
  "木": { reading: "き", meaning: "みきと えだの あるもの" },
  "田": { reading: "た", meaning: "おこめを そだてる所" },
  "川": { reading: "かわ", meaning: "みずが ながれる所" },
  "林": { reading: "はやし", meaning: "木が あつまった所" },
  "森": { reading: "もり", meaning: "木が たくさん ある所" },
  "月": { reading: "つき", meaning: "よぞらに ひかるもの" },
  "車": { reading: "くるま", meaning: "はしる のりもの" },
  "人": { reading: "ひと", meaning: "わたしたち にんげん" },
  "糸": { reading: "いと", meaning: "ほそくて ながいもの" },
  "気": { reading: "き", meaning: "こころや くうき" },
  "玉": { reading: "たま", meaning: "まるい もの" },
  "村": { reading: "むら", meaning: "ひとが くらす 小さな所" },
  "白": { reading: "しろ", meaning: "ゆきのような いろ" },
  "音": { reading: "おと", meaning: "みみで きく ひびき" },
  "火": { reading: "ひ", meaning: "あかく もえるもの" },
  "休": { reading: "やすむ", meaning: "からだを やすめる" },
  "金": { reading: "かね", meaning: "おかねや きんぞく" },
  "土": { reading: "つち", meaning: "じめんの つち" },
  "中": { reading: "なか", meaning: "ものの うちがわ" },
  "力": { reading: "ちから", meaning: "ものを うごかす力" },
  "竹": { reading: "たけ", meaning: "まっすぐ のびる草木" },
  "出": { reading: "でる", meaning: "そとへ うごく" },
  "赤": { reading: "あか", meaning: "りんごのような いろ" },
  "生": { reading: "いきる", meaning: "いのちが ある" },
  "耳": { reading: "みみ", meaning: "おとを きく ところ" },
  "王": { reading: "おう", meaning: "くにの りっぱな人" },
  "口": { reading: "くち", meaning: "ものを たべる所" },
  "年": { reading: "とし", meaning: "一年の ながさ" },
  "草": { reading: "くさ", meaning: "じめんに はえる植物" },
  "名": { reading: "な", meaning: "ひとや ものの なまえ" },
  "夕": { reading: "ゆう", meaning: "ひが しずむ ころ" },
  "町": { reading: "まち", meaning: "ひとが くらす所" },
  "百": { reading: "ひゃく", meaning: "かずの 100" },
  "円": { reading: "えん", meaning: "まるい かたち" },
  "千": { reading: "せん", meaning: "かずの 1000" },
  "立": { reading: "たつ", meaning: "まっすぐ おきる" },
  "花": { reading: "はな", meaning: "きれいに さくもの" },
  "本": { reading: "ほん", meaning: "よむ もの" },
  "犬": { reading: "いぬ", meaning: "わんと なく どうぶつ" },
  "早": { reading: "はやい", meaning: "じかんが まえ" },
  "目": { reading: "め", meaning: "ものを みる ところ" },
  "貝": { reading: "かい", meaning: "からの ある いきもの" },
  "入": { reading: "はいる", meaning: "なかへ すすむ" },
  "右": { reading: "みぎ", meaning: "ひだりの はんたい" },
  "足": { reading: "あし", meaning: "あるく ところ" },
  "石": { reading: "いし", meaning: "かたい いわの かけら" },
  "左": { reading: "ひだり", meaning: "みぎの はんたい" },
  "先": { reading: "さき", meaning: "まえの ほう" },

  "読": { reading: "よむ", meaning: "もじを たどる" },
  "雪": { reading: "ゆき", meaning: "そらから ふる こおり" },
  "言": { reading: "いう", meaning: "ことばを はなす" },
  "行": { reading: "いく", meaning: "むこうへ すすむ" },
  "南": { reading: "みなみ", meaning: "きたの はんたい" },
  "書": { reading: "かく", meaning: "もじを しるす" },
  "絵": { reading: "え", meaning: "かいて あらわすもの" },
  "図": { reading: "ず", meaning: "かたちを かいたもの" },
  "分": { reading: "わける", meaning: "いくつかに わける" },
  "方": { reading: "かた", meaning: "むきや やりかた" },
  "春": { reading: "はる", meaning: "あたたかくなる きせつ" },
  "思": { reading: "おもう", meaning: "こころで かんがえる" },
  "記": { reading: "しるす", meaning: "わすれないように 書く" },
  "曜": { reading: "よう", meaning: "ようびを あらわす字" },
  "肉": { reading: "にく", meaning: "からだを つくるもの" },
  "話": { reading: "はなす", meaning: "ことばで つたえる" },
  "聞": { reading: "きく", meaning: "みみで たしかめる" },
  "黄": { reading: "き", meaning: "たんぽぽの いろ" },
  "色": { reading: "いろ", meaning: "ものの みえかた" },
  "黒": { reading: "くろ", meaning: "すみのような いろ" },
  "太": { reading: "ふとい", meaning: "はばが おおきい" },
  "毛": { reading: "け", meaning: "からだに はえるもの" },
  "高": { reading: "たかい", meaning: "うえまで ながい" },
  "風": { reading: "かぜ", meaning: "うごく くうき" },
  "晴": { reading: "はれる", meaning: "そらが よく はれる" },
  "多": { reading: "おおい", meaning: "かずが たくさん" },
  "形": { reading: "かたち", meaning: "ものの すがた" },
  "長": { reading: "ながい", meaning: "はしから はしが遠い" },
  "数": { reading: "かず", meaning: "いくつ あるか" },
  "体": { reading: "からだ", meaning: "あたまや 手足のぜんぶ" },
  "近": { reading: "ちかい", meaning: "きょりが みじかい" },
  "同": { reading: "おなじ", meaning: "ちがいが ない" },
  "今": { reading: "いま", meaning: "この じかん" },
  "会": { reading: "あう", meaning: "ひとと であう" },
  "社": { reading: "しゃ", meaning: "かいしゃや じんじゃ" },
  "刀": { reading: "かたな", meaning: "はの ある どうぐ" },
  "切": { reading: "きる", meaning: "わけて はなす" },
  "内": { reading: "うち", meaning: "ものの なか" },
  "店": { reading: "みせ", meaning: "ものを うる ところ" },
  "姉": { reading: "あね", meaning: "としうえの おんなの子" },
  "妹": { reading: "いもうと", meaning: "とししたの おんなの子" },
  "線": { reading: "せん", meaning: "ほそく のびる すじ" },
  "汽": { reading: "き", meaning: "あつい みずの けむり" },
  "海": { reading: "うみ", meaning: "ひろい しおみず" },
  "回": { reading: "まわる", meaning: "ぐるりと うごく" },
  "歩": { reading: "あるく", meaning: "あしで すすむ" },
  "魚": { reading: "さかな", meaning: "みずで およぐ いきもの" },
  "広": { reading: "ひろい", meaning: "はばが おおきい" },
  "前": { reading: "まえ", meaning: "むいている ほう" },
  "元": { reading: "もと", meaning: "はじまりの ところ" },
  "岩": { reading: "いわ", meaning: "おおきく かたい石" },
  "教": { reading: "おしえる", meaning: "わかるように つたえる" },
  "光": { reading: "ひかり", meaning: "あかるく てらすもの" },
  "知": { reading: "しる", meaning: "わかるように なる" },
  "考": { reading: "かんがえる", meaning: "あたまで こたえを探す" },
  "室": { reading: "しつ", meaning: "たてものの へや" },
  "組": { reading: "くむ", meaning: "いっしょに あわせる" },
  "後": { reading: "あと", meaning: "うしろや そのつぎ" },
  "丸": { reading: "まる", meaning: "まるい かたち" },
  "点": { reading: "てん", meaning: "ちいさな しるし" },
  "買": { reading: "かう", meaning: "おかねで てに入れる" },
  "友": { reading: "とも", meaning: "なかよしの ひと" },
  "羽": { reading: "はね", meaning: "とりが とぶ ところ" },
  "雲": { reading: "くも", meaning: "そらに うかぶもの" },
  "夏": { reading: "なつ", meaning: "あつい きせつ" },
  "公": { reading: "こう", meaning: "みんなの もの" },
  "園": { reading: "えん", meaning: "ひろい にわや 公園" },
  "通": { reading: "とおる", meaning: "みちを すすむ" },
  "万": { reading: "まん", meaning: "かずの 10000" },
  "頭": { reading: "あたま", meaning: "からだの いちばん上" },
  "鳥": { reading: "とり", meaning: "はねで とぶ いきもの" },
};

const MEANING_OVERRIDES = Object.freeze({
  "愛": "いとしい",
  "案": "あん",
  "意": "こころ",
  "営": "いとなむ",
  "衛": "まもる",
  "応": "こたえる",
  "永": "ながい",
  "協": "あわせる",
  "議": "はなしあい",
  "情": "こころ",
  "証": "あかし",
  "税": "ぜいきん",
  "導": "みちびく",
  "能": "はたらき",
  "報": "しらせる",
  "豊": "ゆたか",
  "防": "ふせぐ",
  "歴": "うつり",
  "録": "しるす",
  "練": "ねる",
  "例": "たとえ",
  "連": "つらなる",
  "量": "はかる",
  "像": "かたち",
  "態": "かたち",
  "提": "さげる",
  "程": "ほど",
  "適": "かなう",
  "復": "もどる",
  "複": "ふたつ",
  "欲": "ほしい",
  "余": "あまる",
  "由": "よし",
});

export function hiraganaize(text) {
  return [...text].map((char) => {
    const code = char.codePointAt(0);
    if (code >= 0x30A1 && code <= 0x30F6) return String.fromCodePoint(code - 0x60);
    return char;
  }).join("");
}

export function normalizeReading(reading) {
  return hiraganaize(reading.replaceAll("-", ""));
}

export function isKunReading(reading) {
  return /[ぁ-ゖ]/.test(reading);
}

export function resolveReading(char, officialReadings) {
  if (READINGS[char]) return READINGS[char].reading;
  const candidates = Array.isArray(officialReadings) ? officialReadings : [];
  const kun = candidates.find((candidate) => isKunReading(candidate));
  return normalizeReading(kun ?? candidates[0] ?? "");
}

export function resolveMeaning(char, reading) {
  if (READINGS[char]) return READINGS[char].meaning;
  return MEANING_OVERRIDES[char] ?? normalizeReading(reading);
}
